# Generated by Django 4.2.5 on 2023-09-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('users', '0001_initial'),
        ('bctoken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('collectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('tokenId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bctoken.token')),
            ],
        ),
    ]
